# Generated by Django 2.2.16 on 2020-11-26 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タイトル')),
            ],
        ),
        migrations.CreateModel(
            name='HeartLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, verbose_name='ユーザID')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='登録時間')),
                ('bpm', models.FloatField(blank=True, verbose_name='心拍数')),
            ],
            options={
                'verbose_name': '心拍データ',
                'verbose_name_plural': '心拍データ',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='タイトル')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='note.Category', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ名')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Note',
            },
        ),
        migrations.CreateModel(
            name='KeyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_at', models.DateTimeField(auto_now_add=True, verbose_name='カウント時間')),
                ('count', models.IntegerField(verbose_name='文字数')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='note.Note', verbose_name='note_id')),
            ],
            options={
                'verbose_name': 'KeyLog',
                'verbose_name_plural': 'KeyLog',
            },
        ),
    ]
