# Generated by Django 2.2.16 on 2021-01-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keylog',
            name='key',
            field=models.IntegerField(blank=True, null=True, verbose_name='キーコード'),
        ),
    ]
