# Generated by Django 2.2.16 on 2021-01-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_keylog_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.TextField(blank=True, null=True, verbose_name='カラー'),
        ),
    ]
